name: get_cli
version: 1.8.2
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  #  archive: ^3.1.2
  ansicolor: ">=2.0.1 <3.0.0"
  collection: any
  dart_style: ">=2.2.5 <3.0.0"
  dcli: ^4.0.4
  http: any
  intl: any
  meta: ">=1.9.1 <2.0.0"
  path: ">=1.8.3 <2.0.0"
  process_run: ">=0.13.0 <1.0.0"
  pubspec: ">=2.3.0 <3.0.0"
  recase: ">=4.1.0 <5.0.0"
  version: ">=3.0.2 <4.0.0"
  yaml: ">=3.1.2 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.5.0

executables:
  get: get
  # getx: get
