name: get_cli
version: 1.9.1
homepage: https://github.com/jonataslaw/get_cli
description: Official CLI for GetX™ framework to build Flutter and Server
  Applications easily

environment:
  sdk: 3.6.0

dependencies:
  #  archive: ^3.1.2
  ansicolor: any
  collection: any
  dart_style: any
  dcli: any
  http: any
  intl: any
  meta: any
  path: any
  process_run: any
  pubspec_parse: any
  pub_semver: any
  recase: any
  version: any
  yaml: any

dev_dependencies:
  lints: any
  test: any

executables:
  get: get
  # getx: get
